"""Added title to posts

Revision ID: 234d3e3de986
Revises: 262f0c6d09ed
Create Date: 2023-04-30 20:27:48.099916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234d3e3de986'
down_revision = '262f0c6d09ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
