"""added columns to Tarot

Revision ID: 262f0c6d09ed
Revises: 23be828a7cc3
Create Date: 2023-04-27 16:26:48.156754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262f0c6d09ed'
down_revision = '23be828a7cc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarots', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
